/** Shared between `AgentMessage.tsx` and `ToolStepsGroup.tsx` — kept in its own file to avoid a circular import. */
export const TOOL_LABELS: Record<string, string> = {
  search_contacts: "Buscando contactos",
  get_contact: "Consultando contacto",
  list_enrollments: "Listando inscripciones",
  get_enrollment: "Consultando inscripción",
  list_products: "Listando productos",
  dashboard_stats: "Consultando estadísticas",
  query_audit_log: "Consultando auditoría",
  create_contact: "Creando contacto",
  create_promo_code: "Creando código promocional",
  update_promo_code: "Actualizando código promocional",
  request_payment_otp: "Enviando código de verificación",
  record_manual_payment: "Registrando pago manual",
  update_usd_to_cop_rate: "Actualizando tasa USD→COP",
  update_product_price: "Actualizando precio",
  create_staff_user: "Creando cuenta de staff",
  list_message_templates: "Listando plantillas de mensajes",
  prepare_customer_whatsapp_message: "Preparando mensaje de WhatsApp",
};
