/** Shared between `AgentMessage.tsx` and `ToolStepsGroup.tsx` — kept in its own file to avoid a circular import. */
export const TOOL_LABELS: Record<string, string> = {
  search_contacts: "Buscando contactos",
  get_contact: "Consultando contacto",
  list_enrollments: "Listando inscripciones",
  get_enrollment: "Consultando inscripción",
  list_products: "Listando productos",
  dashboard_stats: "Consultando estadísticas",
  query_audit_log: "Consultando auditoría",
  create_contact: "Creando contacto",
  create_promo_code: "Creando código promocional",
  update_promo_code: "Actualizando código promocional",
  request_payment_otp: "Enviando código de verificación",
  record_manual_payment: "Registrando pago manual",
  update_usd_to_cop_rate: "Actualizando tasa USD→COP",
  update_product_price: "Actualizando precio",
  create_staff_user: "Creando cuenta de staff",
  list_message_templates: "Listando plantillas de mensajes",
  prepare_customer_whatsapp_message: "Preparando mensaje de WhatsApp",
  whatsapp_ai_status: "Revisando la IA de WhatsApp",
  whatsapp_get_config: "Leyendo la configuración de WhatsApp",
  whatsapp_update_config: "Cambiando la configuración de WhatsApp",
  whatsapp_list_playbooks: "Leyendo los procedimientos de WhatsApp",
  whatsapp_save_playbook: "Guardando un procedimiento de WhatsApp",
  whatsapp_find_chat: "Buscando chats de WhatsApp",
  whatsapp_set_chat: "Cambiando un chat de WhatsApp",
  whatsapp_simulate_reply: "Probando una respuesta de WhatsApp",
  send_whatsapp_to_contact: "Enviando un WhatsApp",
  send_whatsapp_bulk: "Enviando WhatsApp a varias personas",
};
